### ISSUE TITLE
Nuisance with "undefined elements" when clearing the cache(s) (plain vanilla version)

### ISSUE THREAD

**Issue by arvgta** [arvgta/ajaxify#224]
A nuisance has been reported by our partner [AllMediaLab ](https://www.allmedialab.be/)in the plain vanilla version:

- There is an issue with some popping up of "undefined" elements in the console, after clearing the cache(s) (Used to work in the [old jQuery versions](https://cdn.jsdelivr.net/gh/arvgta/ajaxify@7.6.4/)).  **It happens irregularly, i.e. not all of the time!**

[AllMediaLab ](https://www.allmedialab.be/) has reported, that the nuisance happens only in the context of [alwayshints](https://4nf.org/alwayshints/) and can be worked around by placing the respective link on each and every page of the site, which is obviously not the spirit of [delta-loading](https://4nf.org/delta-loading/).

This issue has also [been reported by Sagar](https://4nf.org/demos/#comment-183349)...
(Sagar reported, that the bug seems to be within the `addAll` class)

<hr>

You can also reproduce the issue on http://www.oeko-fakt.de/ :

1. Clear the browser caches
2. From the homepage traverse to "[Produkte](http://www.oeko-fakt.de/produkte/)"
3. Examine the error in the console, which should be similar to the following:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'oApi')
    at produktsuche.js:4:22
    at produktsuche.js:44:6
```

<hr>

Salient code:

```javascript
$this.forEach(function(s) { //Iterate through selection
			var $t = s;
			url = $t.getAttribute(PK);
			if(_classAlways($t)) { //Class always handling
				_removeScript(); //remove from DOM
				_iScript($t); //insert back single external script in the head
				return; //this return may be dodgy, as the URL does not get pushed to the array as below?
			}
			if(url) { //URL?
				if(!$scriptsO.some(e => e == url)) { // Test, whether new
					$scriptsO.push(url); //If yes: Push to old array
					_iScript($t);
				}
				//Otherwise nothing to do
				return;
			}

			if(PK != "href" && !$t.classList.contains("no-ajaxy")) Ay.scripts($t); //Inline JS script? -> inject into DOM
		});
```

<hr>

- If you can reproduce the bug, please consider posting your findings below.

**Comment by arvgta** [comment]
Closing for the moment because there are lots of other open issues...
